import { NextResponse } from 'next/server';

// Personalised narrative impact stories per donation
const IMPACT_STORIES = [
    {
        id: 's1',
        donation_id: 'd1',
        amount: 50000,
        project_title: 'Clean Water for Rural Maharashtra',
        ngo_name: 'GreenFuture Foundation',
        sdg_tags: [6, 3],
        headline: 'Your ₹50,000 brought clean water to 1,200 families in Nashik.',
        story: 'Families in 4 drought-affected villages in Nashik now have access to purified drinking water year-round. Before this project, women and children walked 4+ km daily for water — now a purification unit serves 1,200 people at their doorstep. Your donation directly funded the installation of 3 filtration units.',
        metric_icon: '💧',
        metric_label: '1,200 people',
        metric_sub: 'now have safe water',
        image_seed: 'p1',
        date: '2024-06-15',
        verified: true,
    },
    {
        id: 's2',
        donation_id: 'd2',
        amount: 100000,
        project_title: 'Solar Schools Initiative',
        ngo_name: 'GreenFuture Foundation',
        sdg_tags: [7, 4, 13],
        headline: 'Your ₹1 Lakh lit up 12 solar-powered schools in Rajasthan.',
        story: '12 government schools in Jaipur district now have uninterrupted electricity, enabling digital classrooms, ceiling fans in summer, and evening study hours. Over 3,100 students can now study after sunset, with attendance up by 22% since installation. Your contribution funded solar panel installation and battery packs for 4 schools.',
        metric_icon: '☀️',
        metric_label: '3,100 students',
        metric_sub: 'now study in solar-powered classrooms',
        image_seed: 'p2',
        date: '2024-08-20',
        verified: true,
    },
    {
        id: 's3',
        donation_id: 'd3',
        amount: 75000,
        project_title: 'Tribal Healthcare Access Program',
        ngo_name: 'HealthBridge India',
        sdg_tags: [3, 1, 10],
        headline: 'Your ₹75,000 vaccinated 180 tribal children in Odisha.',
        story: 'HealthBridge India\'s mobile clinic reached 6 tribal villages in Koraput using the funds from donors like you. In two medical camps, 180 children under 5 received full vaccination coverage, and 240 adults were screened for tuberculosis and malaria. A doctor-to-patient ratio that was previously 1:12,000 dropped to 1:800 during the camp.',
        metric_icon: '🏥',
        metric_label: '420 lives',
        metric_sub: 'received critical healthcare',
        image_seed: 'p5',
        date: '2024-10-10',
        verified: true,
    },
    {
        id: 's4',
        donation_id: 'd4',
        amount: 25000,
        project_title: 'Women Skill Development Program',
        ngo_name: 'GreenFuture Foundation',
        sdg_tags: [5, 8],
        headline: 'Your ₹25,000 helped 62 women start digital careers.',
        story: 'In Patna, Bihar, 62 women from low-income households completed a 6-week digital literacy course funded in part by your donation. 38 of them have already found remote work as data entry operators, and 12 have started small online businesses. Average household income in the cohort rose by ₹4,200/month.',
        metric_icon: '👩‍💻',
        metric_label: '62 women',
        metric_sub: 'gained digital employment skills',
        image_seed: 'p3',
        date: '2024-12-01',
        verified: true,
    },
    {
        id: 's5',
        donation_id: 'd7',
        amount: 80000,
        project_title: 'Digital Classrooms for Delhi Slums',
        ngo_name: 'EduRise Foundation',
        sdg_tags: [4, 10],
        headline: 'Your ₹80,000 set up 3 digital learning centers in Delhi.',
        story: 'Three digital learning centres, each equipped with 15 tablets and high-speed internet, now serve 450 children aged 8–16 in Nehru Nagar, Delhi. A volunteer-led after-school coding program runs every evening. Dropout rates in enrolled schools fell by 18% in the 3 months after launch.',
        metric_icon: '📱',
        metric_label: '450 children',
        metric_sub: 'now learn coding & digital skills',
        image_seed: 'p7',
        date: '2024-11-15',
        verified: true,
    },
];

export async function GET() {
    return NextResponse.json({ success: true, data: IMPACT_STORIES });
}
