import { NextResponse } from 'next/server';

// Rich mock data — production would query Prisma
const MOCK_OPPORTUNITIES = [
    {
        id: 'vo1',
        title: 'Mangrove Sapling Plantation Drive',
        description: 'We need eco-conscious individuals to help plant 5,000 mangrove saplings along the Versova coastal stretch to combat soil erosion and restore the marine ecosystem. Gloves, boots, and refreshments provided. This is a high-impact, hands-on conservation event perfect for nature lovers.',
        date: '2026-03-17',
        start_time: '08:00 AM',
        end_time: '01:00 PM',
        location: 'Versova Beach, Mumbai',
        required_volunteers: 150,
        filled_volunteers: 45,
        ngo_name: 'BlueOcean NGO',
        ngo_id: 'org4',
        ngo_logo: null,
        ngo_rating: 4.8,
        ngo_verified: true,
        sdg_tags: [14, 13, 15],
        skills_needed: ['Physical fitness', 'Outdoor enthusiasm', 'Environmental awareness'],
        what_to_bring: ['Comfortable clothes', 'Sunscreen', 'Water bottle'],
        what_provided: ['Gloves', 'Planting tools', 'Breakfast & refreshments', 'Certificate'],
        impact_statement: 'Each volunteer will plant ~33 saplings, preventing approx. 500 kg of coastal erosion annually.',
        hours_commitment: 5,
        category: 'Environment',
        urgency: 'high',
    },
    {
        id: 'vo2',
        title: 'Rural Digital Literacy Bootcamp — Teach Coding to Kids',
        description: 'Join RuralTech Connect in empowering 200+ underprivileged children aged 10–16 with basic coding, internet safety, and digital skills. Volunteers will lead 45-minute interactive sessions. No prior teaching experience needed — just enthusiasm and patience!',
        date: '2026-03-22',
        start_time: '10:00 AM',
        end_time: '04:00 PM',
        location: 'Coimbatore, Tamil Nadu',
        required_volunteers: 40,
        filled_volunteers: 18,
        ngo_name: 'RuralTech Connect',
        ngo_id: 'ngo8',
        ngo_logo: null,
        ngo_rating: 4.9,
        ngo_verified: true,
        sdg_tags: [4, 8, 9],
        skills_needed: ['Basic computer skills', 'Communication', 'Patience with children'],
        what_to_bring: ['Laptop (optional)', 'ID proof'],
        what_provided: ['Training resources', 'Lunch', 'Certificate of volunteering', 'Travel reimbursement within city'],
        impact_statement: 'Each volunteer facilitates digital skills for 5 children, opening pathways to future employment.',
        hours_commitment: 6,
        category: 'Education',
        urgency: 'medium',
    },
    {
        id: 'vo3',
        title: 'Free Health Check-up Camp — Tribal Villages, Odisha',
        description: 'HealthBridge India is organizing a 2-day free medical camp for 80 tribal villages in Koraput district. We need volunteers for patient registration, assistance, awareness drives, and logistics. Medical professionals welcome, but non-medical volunteers equally valued.',
        date: '2026-03-28',
        start_time: '07:00 AM',
        end_time: '05:00 PM',
        location: 'Koraput, Odisha',
        required_volunteers: 80,
        filled_volunteers: 62,
        ngo_name: 'HealthBridge India',
        ngo_id: 'org3',
        ngo_logo: null,
        ngo_rating: 4.7,
        ngo_verified: true,
        sdg_tags: [3, 1, 10],
        skills_needed: ['First aid basics (preferred)', 'Hindi/Odia speaking', 'Empathy & compassion'],
        what_to_bring: ['Medical kit if applicable', 'Comfortable footwear', 'ID proof'],
        what_provided: ['Accommodation', 'All meals', 'Transport from Koraput city', 'Volunteer certificate'],
        impact_statement: 'Last year\'s camp screened 3,200 people. Your one day helps 40+ patients receive critical care.',
        hours_commitment: 10,
        category: 'Healthcare',
        urgency: 'low',
    },
    {
        id: 'vo4',
        title: 'Urban Waste Segregation Awareness Walk',
        description: 'EcoIndia Trust is conducting a city-wide awareness walk across 8 wards of Bengaluru to educate residents about waste segregation under the Swachh Bharat mission. Volunteers will distribute pamphlets, demonstrate correct segregation at homes, and collect feedback.',
        date: '2026-04-05',
        start_time: '07:30 AM',
        end_time: '11:30 AM',
        location: 'Bengaluru, Karnataka',
        required_volunteers: 100,
        filled_volunteers: 28,
        ngo_name: 'EcoIndia Trust',
        ngo_id: 'org2',
        ngo_logo: null,
        ngo_rating: 4.6,
        ngo_verified: true,
        sdg_tags: [11, 12, 13],
        skills_needed: ['Kannada/Hindi speaking preferred', 'Communication', 'Walking fitness'],
        what_to_bring: ['Comfortable shoes', 'Reusable water bottle'],
        what_provided: ['T-shirt', 'Pamphlets & materials', 'Snacks', 'E-certificate'],
        impact_statement: 'Each volunteer covers 1 ward (~2,500 households), potentially diverting 500 kg/month from landfill.',
        hours_commitment: 4,
        category: 'Environment',
        urgency: 'medium',
    },
];

export async function GET() {
    try {
        await new Promise(r => setTimeout(r, 200));
        return NextResponse.json({
            success: true,
            data: MOCK_OPPORTUNITIES,
            timestamp: new Date().toISOString(),
        });
    } catch {
        return NextResponse.json(
            { success: false, error: 'Failed to fetch volunteer opportunities.' },
            { status: 500 }
        );
    }
}
