'use client';
import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

export interface VolunteerHistoryItem {
    id: string;
    opportunity_id: string;
    opportunity_title: string;
    ngo_name: string;
    ngo_id: string;
    date: string;
    hours_contributed: number;
    location: string;
    status: 'COMPLETED' | 'PENDING' | 'CANCELLED';
    certificate_id: string;
    sdg_tags: number[];
    impact_statement: string;
    feedback_submitted: boolean;
    ngo_rating: number | null;
    feedback_text: string | null;
}

const SDG_COLORS: Record<number, string> = {
    1: '#e5243b', 2: '#dda63a', 3: '#4c9f38', 4: '#c5192d', 5: '#ff3a21',
    6: '#26bde2', 7: '#fcc30b', 8: '#a21949', 9: '#fd6e25', 10: '#dd1367',
    11: '#fd9d24', 12: '#bf8b2e', 13: '#3f7e44', 14: '#0a97d9', 15: '#56c02b',
    16: '#0056c8', 17: '#19486a',
};

// ── Cert download (browser-side PDF-like HTML print) ──────────────────────
function downloadCertificate(item: VolunteerHistoryItem) {
    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title>Volunteer Certificate</title>
  <style>
    body { margin:0; font-family:'Segoe UI',Arial,sans-serif; background:#f0f4f8; display:flex; align-items:center; justify-content:center; min-height:100vh; }
    .cert { background: white; width: 720px; padding: 60px; border: 3px solid #10b981; border-radius: 16px; box-shadow: 0 8px 40px rgba(0,0,0,0.12); text-align:center; }
    .logo { font-size: 48px; margin-bottom: 10px; }
    .brand { font-size: 22px; font-weight: 800; color: #10b981; letter-spacing: 2px; margin-bottom: 6px; }
    .sub { font-size: 13px; color: #94a3b8; margin-bottom: 30px; }
    .divider { border: none; border-top: 2px solid #e2e8f0; margin: 24px auto; width: 80%; }
    h1 { font-size: 28px; color: #0f172a; margin: 0 0 10px; }
    .name { font-size: 22px; font-weight: 700; color: #1e40af; margin: 16px 0 24px; }
    .detail { font-size: 15px; color: #475569; margin: 8px 0; }
    .impact { background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 10px; padding: 16px; margin: 24px 0; font-size: 13px; color: #166534; font-style: italic; }
    .cert-id { font-size: 11px; color: #94a3b8; margin-top: 30px; }
    .footer { font-size: 11px; color: #cbd5e1; margin-top: 10px; }
    .stamp { display:inline-block; border: 3px solid #10b981; border-radius: 50%; padding: 12px 16px; color: #10b981; font-weight: 800; font-size: 13px; margin-top: 20px; }
  </style>
</head>
<body>
  <div class="cert">
    <div class="logo">🌍</div>
    <div class="brand">SDG NEXUS</div>
    <div class="sub">United Nations Sustainable Development Goals Platform</div>
    <hr class="divider"/>
    <h1>Certificate of Volunteering</h1>
    <p class="detail">This is to certify that</p>
    <p class="name">Vikram Patel</p>
    <p class="detail">has successfully volunteered at</p>
    <p class="detail"><strong>${item.opportunity_title}</strong></p>
    <p class="detail">organised by <strong>${item.ngo_name}</strong></p>
    <p class="detail">on <strong>${new Date(item.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</strong></p>
    <p class="detail">Duration: <strong>${item.hours_contributed} Hours</strong> &nbsp;|&nbsp; Location: <strong>${item.location}</strong></p>
    <div class="impact">"${item.impact_statement}"</div>
    <div class="stamp">✓ VERIFIED</div>
    <p class="cert-id">Certificate ID: ${item.certificate_id}</p>
    <p class="footer">Generated by SDG Nexus · sdgnexus.org · This certificate is digitally verifiable.</p>
  </div>
</body>
</html>`;
    const win = window.open('', '_blank');
    if (win) { win.document.write(html); win.document.close(); win.print(); }
}

// ── Star Rating ───────────────────────────────────────────────────────────
function StarRating({ value, onChange }: { value: number; onChange: (v: number) => void }) {
    const [hover, setHover] = useState(0);
    return (
        <div className="flex gap-1">
            {[1, 2, 3, 4, 5].map(star => (
                <button key={star} type="button"
                    onMouseEnter={() => setHover(star)}
                    onMouseLeave={() => setHover(0)}
                    onClick={() => onChange(star)}
                    className="text-2xl transition-transform hover:scale-110">
                    <span style={{ color: star <= (hover || value) ? '#f59e0b' : '#e2e8f0' }}>★</span>
                </button>
            ))}
        </div>
    );
}

// ── Feedback Modal ────────────────────────────────────────────────────────
function FeedbackModal({ item, onClose, onSubmit }: {
    item: VolunteerHistoryItem;
    onClose: () => void;
    onSubmit: (id: string, rating: number, text: string) => void;
}) {
    const [rating, setRating] = useState(5);
    const [text, setText] = useState('');
    const [submitting, setSubmitting] = useState(false);

    const handleSubmit = async () => {
        if (!text.trim() || rating < 1) return;
        setSubmitting(true);
        await onSubmit(item.id, rating, text);
        setSubmitting(false);
        onClose();
    };

    return (
        <div className="fixed inset-0 z-[60] flex items-center justify-center p-4"
            style={{ background: 'rgba(0,0,0,0.65)', backdropFilter: 'blur(6px)' }}
            onClick={onClose}>
            <motion.div initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }}
                className="bg-white rounded-2xl shadow-2xl p-6 w-full max-w-lg"
                onClick={e => e.stopPropagation()}>
                <div className="flex items-center justify-between mb-4">
                    <h3 className="text-lg font-bold text-slate-900">Rate & Review NGO</h3>
                    <button onClick={onClose} className="text-slate-400 hover:text-slate-600 text-xl">✕</button>
                </div>

                <div className="p-4 rounded-xl mb-4" style={{ background: '#f8fafc', border: '1px solid #e2e8f0' }}>
                    <p className="text-xs text-slate-500 mb-0.5">You volunteered at</p>
                    <p className="text-sm font-semibold text-slate-900">{item.opportunity_title}</p>
                    <p className="text-xs text-slate-500 mt-0.5">by {item.ngo_name} · {new Date(item.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}</p>
                </div>

                <div className="mb-4">
                    <label className="block text-xs font-semibold text-slate-600 mb-2">
                        Rate this NGO&apos;s work authenticity & impact *
                    </label>
                    <StarRating value={rating} onChange={setRating} />
                    <p className="text-xs mt-1 text-slate-400">
                        {rating === 5 ? 'Excellent — highly authentic, transparent, impactful'
                            : rating === 4 ? 'Very good — genuine work with minor gaps'
                                : rating === 3 ? 'Average — some concerns but generally honest'
                                    : rating === 2 ? 'Poor — significant authenticity concerns'
                                        : 'Very poor — highly questionable practices'}
                    </p>
                </div>

                <div className="mb-5">
                    <label className="block text-xs font-semibold text-slate-600 mb-2">
                        Your detailed feedback (as a firsthand volunteer witness) *
                    </label>
                    <textarea
                        value={text}
                        onChange={e => setText(e.target.value)}
                        rows={4}
                        className="w-full px-3 py-2.5 rounded-xl border text-sm outline-none resize-none focus:ring-2 focus:ring-blue-500"
                        style={{ borderColor: '#e2e8f0', color: '#1e293b' }}
                        placeholder="Describe what you observed — Was the stated mission being executed? Were resources used properly? How were beneficiaries treated? Any transparency concerns?"
                    />
                    <p className="text-[10px] text-slate-400 mt-1">{text.length}/500 characters</p>
                </div>

                <div className="p-3 rounded-lg mb-4 text-xs" style={{ background: 'rgba(59,130,246,0.06)', border: '1px solid rgba(59,130,246,0.2)', color: '#1e40af' }}>
                    ℹ️ Your review will be anonymised and shared with government regulators and corporate CSR teams to ensure NGO accountability on SDG Nexus.
                </div>

                <div className="flex gap-3">
                    <button onClick={onClose}
                        className="flex-none px-4 py-2.5 rounded-xl text-sm font-semibold"
                        style={{ background: '#f1f5f9', color: '#64748b' }}>
                        Cancel
                    </button>
                    <button
                        onClick={handleSubmit}
                        disabled={submitting || !text.trim() || rating < 1}
                        className="flex-1 py-2.5 rounded-xl text-sm font-bold text-white disabled:opacity-50 transition-all"
                        style={{ background: 'linear-gradient(135deg,#3b82f6,#06b6d4)' }}>
                        {submitting ? 'Submitting...' : 'Submit Feedback'}
                    </button>
                </div>
            </motion.div>
        </div>
    );
}

// ── Main History Component ────────────────────────────────────────────────
interface Props {
    items: VolunteerHistoryItem[];
    totalHours: number;
    onFeedbackSubmitted: (id: string) => void;
}

export default function VolunteerHistory({ items, totalHours, onFeedbackSubmitted }: Props) {
    const [feedbackTarget, setFeedbackTarget] = useState<VolunteerHistoryItem | null>(null);
    const [submittedSet, setSubmittedSet] = useState<Set<string>>(new Set());

    const handleFeedbackSubmit = async (id: string, rating: number, text: string) => {
        const item = items.find(i => i.id === id);
        if (!item) return;
        try {
            await fetch('/api/donor/volunteer-feedback', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ application_id: id, ngo_id: item.ngo_id, rating, feedback_text: text }),
            });
            setSubmittedSet(prev => new Set([...prev, id]));
            onFeedbackSubmitted(id);
        } catch (e) { console.error(e); }
    };

    if (items.length === 0) {
        return (
            <div className="text-center py-10">
                <div className="text-4xl mb-3">🙋</div>
                <p className="text-sm text-slate-500 font-medium">No completed volunteering yet.</p>
                <p className="text-xs text-slate-400 mt-1">Apply to an opportunity above and your records will appear here after completion.</p>
            </div>
        );
    }

    return (
        <>
            {/* Summary bar */}
            <div className="grid grid-cols-3 gap-3 mb-5">
                {[
                    { label: 'Events Completed', value: items.filter(i => i.status === 'COMPLETED').length, icon: '✅', color: '#10b981' },
                    { label: 'Total Hours', value: totalHours, icon: '⏱️', color: '#3b82f6' },
                    { label: 'Reviews Given', value: items.filter(i => i.feedback_submitted || submittedSet.has(i.id)).length, icon: '⭐', color: '#f59e0b' },
                ].map(stat => (
                    <div key={stat.label} className="p-4 rounded-xl text-center"
                        style={{ background: stat.color + '0d', border: `1px solid ${stat.color}30` }}>
                        <p className="text-2xl mb-1">{stat.icon}</p>
                        <p className="text-2xl font-bold" style={{ color: stat.color }}>{stat.value}</p>
                        <p className="text-[10px] text-slate-500 mt-0.5">{stat.label}</p>
                    </div>
                ))}
            </div>

            {/* History list */}
            <div className="space-y-4">
                {items.map((item, i) => {
                    const alreadyFeedback = item.feedback_submitted || submittedSet.has(item.id);
                    return (
                        <motion.div key={item.id}
                            initial={{ opacity: 0, y: 12 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: i * 0.08 }}
                            className="rounded-xl overflow-hidden"
                            style={{ border: '1px solid #e2e8f0' }}>

                            {/* Status header */}
                            <div className="px-4 py-3 flex items-center justify-between"
                                style={{ background: item.status === 'COMPLETED' ? 'rgba(16,185,129,0.06)' : '#f8fafc' }}>
                                <div className="flex items-center gap-2">
                                    <span className="text-lg">{item.status === 'COMPLETED' ? '✅' : '⏳'}</span>
                                    <div>
                                        <p className="text-sm font-semibold text-slate-900">{item.opportunity_title}</p>
                                        <p className="text-xs text-slate-500">{item.ngo_name} · {new Date(item.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}</p>
                                    </div>
                                </div>
                                <span className="text-xs font-bold px-2 py-1 rounded-full"
                                    style={{ background: item.status === 'COMPLETED' ? 'rgba(16,185,129,0.12)' : 'rgba(245,158,11,0.12)', color: item.status === 'COMPLETED' ? '#10b981' : '#f59e0b' }}>
                                    {item.status}
                                </span>
                            </div>

                            <div className="p-4">
                                {/* Meta */}
                                <div className="flex flex-wrap gap-3 text-xs text-slate-500 mb-3">
                                    <span>📍 {item.location}</span>
                                    <span>⏱️ {item.hours_contributed} hrs</span>
                                    <span>🏅 {item.certificate_id}</span>
                                </div>

                                {/* SDG tags */}
                                <div className="flex gap-1.5 mb-3 flex-wrap">
                                    {item.sdg_tags.map(t => (
                                        <span key={t} className="text-[10px] font-bold px-2 py-0.5 rounded"
                                            style={{ background: (SDG_COLORS[t] || '#3b82f6') + '20', color: SDG_COLORS[t] || '#3b82f6' }}>
                                            SDG {t}
                                        </span>
                                    ))}
                                </div>

                                {/* Impact */}
                                <p className="text-xs text-slate-600 italic mb-4 leading-relaxed"
                                    style={{ borderLeft: '3px solid #10b981', paddingLeft: '10px' }}>
                                    {item.impact_statement}
                                </p>

                                {/* Submitted feedback display */}
                                {alreadyFeedback && (
                                    <div className="p-3 rounded-lg mb-3 text-xs"
                                        style={{ background: 'rgba(245,158,11,0.06)', border: '1px solid rgba(245,158,11,0.2)' }}>
                                        <p className="font-semibold mb-1" style={{ color: '#b45309' }}>Your Review</p>
                                        <div className="flex gap-0.5 mb-1">
                                            {[1, 2, 3, 4, 5].map(s => (
                                                <span key={s} style={{ color: s <= (item.ngo_rating || 5) ? '#f59e0b' : '#e2e8f0' }}>★</span>
                                            ))}
                                        </div>
                                        {item.feedback_text && <p className="text-slate-600">{item.feedback_text}</p>}
                                    </div>
                                )}

                                {/* Action buttons */}
                                <div className="flex gap-2">
                                    {item.status === 'COMPLETED' && (
                                        <button
                                            onClick={() => downloadCertificate(item)}
                                            className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold transition-all hover:shadow-sm"
                                            style={{ background: 'rgba(59,130,246,0.08)', color: '#3b82f6', border: '1px solid rgba(59,130,246,0.2)' }}>
                                            📄 Download Certificate
                                        </button>
                                    )}
                                    {item.status === 'COMPLETED' && !alreadyFeedback && (
                                        <button
                                            onClick={() => setFeedbackTarget(item)}
                                            className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold transition-all hover:shadow-sm"
                                            style={{ background: 'rgba(245,158,11,0.08)', color: '#b45309', border: '1px solid rgba(245,158,11,0.25)' }}>
                                            ⭐ Rate This NGO
                                        </button>
                                    )}
                                    {alreadyFeedback && (
                                        <span className="flex items-center gap-1 px-3 py-2 rounded-lg text-xs font-semibold"
                                            style={{ background: 'rgba(16,185,129,0.08)', color: '#10b981', border: '1px solid rgba(16,185,129,0.2)' }}>
                                            ✓ Review Submitted
                                        </span>
                                    )}
                                </div>
                            </div>
                        </motion.div>
                    );
                })}
            </div>

            <AnimatePresence>
                {feedbackTarget && (
                    <FeedbackModal
                        item={feedbackTarget}
                        onClose={() => setFeedbackTarget(null)}
                        onSubmit={handleFeedbackSubmit}
                    />
                )}
            </AnimatePresence>
        </>
    );
}
